project_name: alist-cli
before:
  hooks:
    - go mod tidy
builds:
  -
    env:
      - CGO_ENABLED=0
    goos: # 编译平台列表 
      - linux
      - windows
      - darwin
    goarch:
      - arm
      - arm64
      - "386"
      - amd64
    goarm:
      - "7"
    ldflags: 
      - "-s -w"
    ignore:
      - goarch: arm
        goos: windows
      - goarch: arm64
        goos: windows
checksum:
  name_template: 'checksums.txt'
archives:
  - 
    format: binary
    name_template: '{{ tolower .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ replace .Arch "386" "x86" }}{{ with .Arm }}v{{ . }}{{ end }}'
    